version: "3"

services:
  # Continuous file synchronizatio
  syncthing:
    image: syncthing/syncthing:1.21.0
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    volumes:
      - $VOLUMES_DIR/syncthing/config:/var/syncthing/config
      - $VOLUMES_DIR/syncthing/data:/var/syncthing/data
  
  # Sort files as their received from syncthing
  photosort:
    image: negrel/photosort:v0.5.1
    restart: always
    volumes:
      - $VOLUMES_DIR/photosort/config.toml:/etc/photosort.toml:ro
        # Map photosort source directory with syncthing folder path
      - $VOLUMES_DIR/syncthing/data:/src:ro
      - $VOLUMES_DIR/photosort/data:/dst

  photoview:
    image: viktorstrate/photoview:2.3.13
    restart: always
    ports:
      - "8000:80"

    environment:
      - PHOTOVIEW_DATABASE_DRIVER=sqlite
      - PHOTOVIEW_SQLITE_URL=/data/photoview.db
      - PHOTOVIEW_LISTEN_IP=0.0.0.0
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache

      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      # - MAPBOX_TOKEN=<YOUR TOKEN HERE>

    volumes:
      # Map photosort output directory to photoview source directory
      - $VOLUMES_DIR/photosort/data:/photos:ro
      - $VOLUMES_DIR/photoview/data:/data
      - api_cache:/app/cache

volumes:
  api_cache: {}
  data: {}
